### ISSUE TITLE
markdown  git  hub spaced after the headers /usage

### ISSUE THREAD

**Issue by wimbeaumont** [alexander-lee/markdown-github-bear-toc#3]
When there are spaces after the header  

so 
# Tilte<space>  
The link created doesn't work.
Could be mentioned in the usage of the program. (not sure if removing the spaces is a correct action) 

For none daily python user (on windows )   pip install is not sufficient . Obvious (afterwards) a file markdown_toc.py  ( import markdowntoc markdowntoc.main()  ) has to be created. Perhaps could also be in the documentation. 

Thanks making this public.

**Comment by alexander-lee** [comment]
Just looked into this, found the issue. Trimming the spaces solves the problem since I was unconditionally replacing spaces with dashes (-). 

Mind giving me more information on why `pip install` isn't sufficient? Like any specific error messages?
