### ISSUE TITLE
ToC not automatically inserted into Bear notes

### ISSUE THREAD

**Issue by purgat0ri** [alexander-lee/markdown-github-bear-toc#5]
Running the following:

`$ markdown-toc -h 3 -t bear --no-write "💬 Recasting"` 

Works perfectly fine. However, if I were to omit the `--no-write` flag, nothing would actually be added to the Bear note specified. Moreover, if I attempt to run the command again, but with the `--no-write`` flag included to circumvent this error, the following output is shown:

```bash
$ markdown-toc -h 3 -t bear "💬 Recasting"
Creating a Table of Contents for '💬 Recasting'

$ markdown-toc -h 3 -t bear --no-write "💬 Recasting"
[WARNING]: '💬 Recasting' already has a Table of Contents, Ignoring...
```

**Comment by zenglekidd** [comment]
@purgat0ri Same here. Restarting 'Bear' app fixed it for me. MacOS Catalina Version 10.15.

**Comment by alexander-lee** [comment]
Yeah, the strange issue is that (from the last time I checked) there is no way to force Bear to auto-rerender since this is updating the sqlite file that stores the information Bear reads from.

Until Bear has an API that lets you write to a note programmatically, the best bet is to restart Bear 😞
